 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TAnnotation = {
  id?: string;
  extension?: TExtension[];
  authorReference?: TReference;
  authorString?: string;
  time?: TDateTime;
  text: TMarkdown;
};
