/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TBase64Binary } from '../simpleTypes/Base64Binary';

export type TAuditEventDetail = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: string;
  valueString?: string;
  valueBase64Binary?: TBase64Binary;
};
