 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDecimal } from '../simpleTypes/Decimal';
import { TPeriod } from '../partials/Period';

export type TBiologicallyDerivedProductStorage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  temperature?: TDecimal;
  scale?: string;
  duration?: TPeriod;
};
