/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';

export type TBiologicallyDerivedProductManipulation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  timeDateTime?: TDateTime;
  timePeriod?: TPeriod;
};
