/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TInstant } from '../simpleTypes/Instant';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';

export type TBundleResponse = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  status: string;
  location?: TUri;
  etag?: string;
  lastModified?: TInstant;
  outcome?: TResourceContainer;
};
