 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TInstant } from '../simpleTypes/Instant';

export type TBundleRequest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  method: string;
  url: TUri;
  ifNoneMatch?: string;
  ifModifiedSince?: TInstant;
  ifMatch?: string;
  ifNoneExist?: string;
};
