/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDecimal } from '../simpleTypes/Decimal';

export type TBundleSearch = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  mode?: string;
  score?: TDecimal;
};
