 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TCanonical } from '../simpleTypes/Canonical';

export type TCapabilityStatementDocument = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  mode: string;
  documentation?: TMarkdown;
  profile: TCanonical;
};
