 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';

export type TCapabilityStatementSupportedMessage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  mode: string;
  definition: TCanonical;
};
