 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TCapabilityStatementOperation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  definition: TCanonical;
  documentation?: TMarkdown;
};
