 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUrl } from '../simpleTypes/Url';
import { TReference } from '../partials/Reference';

export type TCapabilityStatementImplementation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description: string;
  url?: TUrl;
  custodian?: TReference;
};
