 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TCapabilityStatementInteraction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  documentation?: TMarkdown;
};
