/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDate } from '../simpleTypes/Date';

export type TCitationDateOfPublication = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  date?: TDate;
  year?: string;
  month?: string;
  day?: string;
  season?: string;
  text?: string;
};
