 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';

export type TCitationWhoClassified = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  person?: TReference;
  organization?: TReference;
  publisher?: TReference;
  classifierCopyright?: string;
  freeToShare?: boolean;
};
