/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCitationEntry } from '../partials/CitationEntry';
import { TCitationSummary1 } from '../partials/CitationSummary1';

export type TCitationContributorship = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  complete?: boolean;
  entry?: TCitationEntry[];
  summary?: TCitationSummary1[];
};
