/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';

export type TCitationPublishedIn = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  identifier?: TIdentifier[];
  title?: string;
  publisher?: TReference;
  publisherLocation?: string;
};
