 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCoding } from '../partials/Coding';
import { TInt } from '../simpleTypes/Int';
import { TDateTime } from '../simpleTypes/DateTime';
import { TDecimal } from '../simpleTypes/Decimal';

export type TCodeSystemProperty1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  valueCode?: string;
  valueCoding?: TCoding;
  valueString?: string;
  valueInteger?: TInt;
  valueBoolean?: boolean;
  valueDateTime?: TDateTime;
  valueDecimal?: TDecimal;
};
