 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCoding } from '../partials/Coding';

export type TCodeSystemDesignation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  language?: string;
  use?: TCoding;
  value: string;
};
