 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TCodeSystemFilter = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  description?: string;
  operator: string[];
  value: string;
};
