 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TAttachment } from '../partials/Attachment';
import { TReference } from '../partials/Reference';

export type TCommunicationPayload = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  contentString?: string;
  contentAttachment?: TAttachment;
  contentReference?: TReference;
};
