/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';

export type TCompositionRelatesTo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  targetIdentifier?: TIdentifier;
  targetReference?: TReference;
};
