/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TConceptMapTarget } from '../partials/ConceptMapTarget';

export type TConceptMapElement = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: string;
  display?: string;
  target?: TConceptMapTarget[];
};
