 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TConceptMapDependsOn } from '../partials/ConceptMapDependsOn';

export type TConceptMapTarget = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: string;
  display?: string;
  equivalence: string;
  comment?: string;
  dependsOn?: TConceptMapDependsOn[];
  product?: TConceptMapDependsOn[];
};
