 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TCanonical } from '../simpleTypes/Canonical';

export type TConceptMapDependsOn = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  property: TUri;
  system?: TCanonical;
  value: string;
  display?: string;
};
