 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';

export type TConsentVerification = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  verified: boolean;
  verifiedWith?: TReference;
  verificationDate?: TDateTime;
};
