 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TContractParty } from '../partials/ContractParty';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TContractAnswer } from '../partials/ContractAnswer';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TContractOffer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  party?: TContractParty[];
  topic?: TReference;
  type?: TCodeableConcept;
  decision?: TCodeableConcept;
  decisionMode?: TCodeableConcept[];
  answer?: TContractAnswer[];
  text?: string;
  linkId?: string[];
  securityLabelNumber?: TUnsignedInt[];
};
