/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TContactPoint } from '../partials/ContactPoint';

export type TContactDetail = {
  id?: string;
  extension?: TExtension[];
  name?: string;
  telecom?: TContactPoint[];
};
