 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TContractSubject } from '../partials/ContractSubject';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TTiming } from '../partials/Timing';
import { TAnnotation } from '../partials/Annotation';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TContractAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  doNotPerform?: boolean;
  type: TCodeableConcept;
  subject?: TContractSubject[];
  intent: TCodeableConcept;
  linkId?: string[];
  status: TCodeableConcept;
  context?: TReference;
  contextLinkId?: string[];
  occurrenceDateTime?: TDateTime;
  occurrencePeriod?: TPeriod;
  occurrenceTiming?: TTiming;
  requester?: TReference[];
  requesterLinkId?: string[];
  performerType?: TCodeableConcept[];
  performerRole?: TCodeableConcept;
  performer?: TReference;
  performerLinkId?: string[];
  reasonCode?: TCodeableConcept[];
  reasonReference?: TReference[];
  reason?: string[];
  reasonLinkId?: string[];
  note?: TAnnotation[];
  securityLabelNumber?: TUnsignedInt[];
};
