 
 
// This file is auto-generated by generate_types so do not edit manually

import { TDecimal } from '../simpleTypes/Decimal';
import { TUri } from '../simpleTypes/Uri';

export type TCount = {
  value?: TDecimal;
  comparator?: string;
  unit?: string;
  system?: TUri;
  code?: string;
};
