/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';
import { TCoverageEligibilityResponseItem } from '../partials/CoverageEligibilityResponseItem';

export type TCoverageEligibilityResponseInsurance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  coverage: TReference;
  inforce?: boolean;
  benefitPeriod?: TPeriod;
  item?: TCoverageEligibilityResponseItem[];
};
