/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TCoverageEligibilityResponseBenefit } from '../partials/CoverageEligibilityResponseBenefit';
import { TUri } from '../simpleTypes/Uri';

export type TCoverageEligibilityResponseItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category?: TCodeableConcept;
  productOrService?: TCodeableConcept;
  modifier?: TCodeableConcept[];
  provider?: TReference;
  excluded?: boolean;
  name?: string;
  description?: string;
  network?: TCodeableConcept;
  unit?: TCodeableConcept;
  term?: TCodeableConcept;
  benefit?: TCoverageEligibilityResponseBenefit[];
  authorizationRequired?: boolean;
  authorizationSupporting?: TCodeableConcept[];
  authorizationUrl?: TUri;
};
