/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TMoney } from '../partials/Money';

export type TCoverageEligibilityResponseBenefit = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  allowedUnsignedInt?: TUnsignedInt;
  allowedString?: string;
  allowedMoney?: TMoney;
  usedUnsignedInt?: TUnsignedInt;
  usedString?: string;
  usedMoney?: TMoney;
};
