 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TDataRequirementSort = {
  id?: string;
  extension?: TExtension[];
  path: string;
  direction: string;
};
