 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TQuantity } from '../partials/Quantity';

export type TDataRequirementDateFilter = {
  id?: string;
  extension?: TExtension[];
  path?: string;
  searchParam?: string;
  valueDateTime?: TDateTime;
  valuePeriod?: TPeriod;
  valueDuration?: TQuantity;
};
