 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TDeviceDefinitionSpecialization = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  systemType: string;
  version?: string;
};
