 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TBase64Binary } from '../simpleTypes/Base64Binary';

export type TDeviceUdiCarrier = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  deviceIdentifier?: string;
  issuer?: TUri;
  jurisdiction?: TUri;
  carrierAIDC?: TBase64Binary;
  carrierHRF?: string;
  entryType?: string;
};
