/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInstant } from '../simpleTypes/Instant';

export type TDeviceMetricCalibration = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: string;
  state?: string;
  time?: TInstant;
};
