 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TElementDefinitionBase = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  path: string;
  min: TUnsignedInt;
  max: string;
};
