 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TCanonical } from '../simpleTypes/Canonical';

export type TElementDefinitionType = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TUri;
  profile?: TCanonical[];
  targetProfile?: TCanonical[];
  aggregation?: string[];
  versioning?: string;
};
