 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TElementDefinitionDiscriminator } from '../partials/ElementDefinitionDiscriminator';

export type TElementDefinitionSlicing = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  discriminator?: TElementDefinitionDiscriminator[];
  description?: string;
  ordered?: boolean;
  rules: string;
};
