/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';

export type TElementDefinitionMapping = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identity: TId;
  language?: string;
  map: string;
  comment?: string;
};
