/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';
import { TCanonical } from '../simpleTypes/Canonical';

export type TElementDefinitionConstraint = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  key: TId;
  requirements?: string;
  severity: string;
  human: string;
  expression?: string;
  xpath?: string;
  source?: TCanonical;
};
