/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';

export type TElementDefinitionBinding = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  strength: string;
  description?: string;
  valueSet?: TCanonical;
};
