 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TPeriod } from '../partials/Period';

export type TEpisodeOfCareStatusHistory = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  status: string;
  period: TPeriod;
};
