/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TExpression } from '../partials/Expression';
import { TEvidenceVariableTimeFromStart } from '../partials/EvidenceVariableTimeFromStart';

export type TEvidenceVariableCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  definitionReference?: TReference;
  definitionCanonical?: TCanonical;
  definitionCodeableConcept?: TCodeableConcept;
  definitionExpression?: TExpression;
  method?: TCodeableConcept;
  device?: TReference;
  exclude?: boolean;
  timeFromStart?: TEvidenceVariableTimeFromStart;
  groupMeasure?: string;
};
