/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TPeriod } from '../partials/Period';

export type TEvidenceReportCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  valueReference?: TReference;
  valueCodeableConcept?: TCodeableConcept;
  valueBoolean?: boolean;
  valueQuantity?: TQuantity;
  valueRange?: TRange;
  exclude?: boolean;
  period?: TPeriod;
};
