 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TNarrative } from '../partials/Narrative';
import { TQuantity } from '../partials/Quantity';

export type TEvidenceReportSection = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  title?: string;
  focus?: TCodeableConcept;
  focusReference?: TReference;
  author?: TReference[];
  text?: TNarrative;
  mode?: string;
  orderedBy?: TCodeableConcept;
  entryClassifier?: TCodeableConcept[];
  entryReference?: TReference[];
  entryQuantity?: TQuantity[];
  emptyReason?: TCodeableConcept;
  section?: TEvidenceReportSection[];
};
