 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TAnnotation } from '../partials/Annotation';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TDecimal } from '../simpleTypes/Decimal';
import { TRange } from '../partials/Range';

export type TEvidenceAttributeEstimate = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  note?: TAnnotation[];
  type?: TCodeableConcept;
  quantity?: TQuantity;
  level?: TDecimal;
  range?: TRange;
  attributeEstimate?: TEvidenceAttributeEstimate[];
};
