 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TExampleScenarioProcess } from '../partials/ExampleScenarioProcess';
import { TExampleScenarioOperation } from '../partials/ExampleScenarioOperation';
import { TExampleScenarioAlternative } from '../partials/ExampleScenarioAlternative';

export type TExampleScenarioStep = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  process?: TExampleScenarioProcess[];
  pause?: boolean;
  operation?: TExampleScenarioOperation;
  alternative?: TExampleScenarioAlternative[];
};
