 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TExampleScenarioVersion = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  versionId: string;
  description: TMarkdown;
};
