 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TExampleScenarioContainedInstance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  resourceId: string;
  versionId?: string;
};
