/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TExampleScenarioContainedInstance } from '../partials/ExampleScenarioContainedInstance';

export type TExampleScenarioOperation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  number: string;
  type?: string;
  name?: string;
  initiator?: string;
  receiver?: string;
  description?: TMarkdown;
  initiatorActive?: boolean;
  receiverActive?: boolean;
  request?: TExampleScenarioContainedInstance;
  response?: TExampleScenarioContainedInstance;
};
