/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TExampleScenarioStep } from '../partials/ExampleScenarioStep';

export type TExampleScenarioAlternative = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  title: string;
  description?: TMarkdown;
  step?: TExampleScenarioStep[];
};
