/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TExampleScenarioActor = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  actorId: string;
  type: string;
  name?: string;
  description?: TMarkdown;
};
