 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';
import { TUri } from '../simpleTypes/Uri';

export type TExpression = {
  id?: string;
  extension?: TExtension[];
  description?: string;
  name?: TId;
  language: string;
  expression?: string;
  reference?: TUri;
};
