/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TPeriod } from '../partials/Period';
import { TAnnotation } from '../partials/Annotation';

export type TFamilyMemberHistoryCondition = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  outcome?: TCodeableConcept;
  contributedToDeath?: boolean;
  onsetAge?: TQuantity;
  onsetRange?: TRange;
  onsetPeriod?: TPeriod;
  onsetString?: string;
  note?: TAnnotation[];
};
