 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TInt } from '../simpleTypes/Int';
import { TRatio } from '../partials/Ratio';
import { TDate } from '../simpleTypes/Date';

export type TGoalTarget = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  measure?: TCodeableConcept;
  detailQuantity?: TQuantity;
  detailRange?: TRange;
  detailCodeableConcept?: TCodeableConcept;
  detailString?: string;
  detailBoolean?: boolean;
  detailInteger?: TInt;
  detailRatio?: TRatio;
  dueDate?: TDate;
  dueDuration?: TQuantity;
};
