 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TGraphDefinitionTarget } from '../partials/GraphDefinitionTarget';

export type TGraphDefinitionLink = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  path?: string;
  sliceName?: string;
  min?: TInt;
  max?: string;
  description?: string;
  target?: TGraphDefinitionTarget[];
};
