/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TGraphDefinitionCompartment } from '../partials/GraphDefinitionCompartment';
import { TGraphDefinitionLink } from '../partials/GraphDefinitionLink';

export type TGraphDefinitionTarget = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: string;
  params?: string;
  profile?: TCanonical;
  compartment?: TGraphDefinitionCompartment[];
  link?: TGraphDefinitionLink[];
};
