 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';

export type TGroupCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  valueCodeableConcept?: TCodeableConcept;
  valueBoolean?: boolean;
  valueQuantity?: TQuantity;
  valueRange?: TRange;
  valueReference?: TReference;
  exclude: boolean;
  period?: TPeriod;
};
