 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TPeriod } from '../partials/Period';

export type THealthcareServiceNotAvailable = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description: string;
  during?: TPeriod;
};
