/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TImmunizationRecommendationDateCriterion } from '../partials/ImmunizationRecommendationDateCriterion';
import { TInt } from '../simpleTypes/Int';
import { TReference } from '../partials/Reference';

export type TImmunizationRecommendationRecommendation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  vaccineCode?: TCodeableConcept[];
  targetDisease?: TCodeableConcept;
  contraindicatedVaccineCode?: TCodeableConcept[];
  forecastStatus: TCodeableConcept;
  forecastReason?: TCodeableConcept[];
  dateCriterion?: TImmunizationRecommendationDateCriterion[];
  description?: string;
  series?: string;
  doseNumberPositiveInt?: TInt;
  doseNumberString?: string;
  seriesDosesPositiveInt?: TInt;
  seriesDosesString?: string;
  supportingImmunization?: TReference[];
  supportingPatientInformation?: TReference[];
};
