/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TInt } from '../simpleTypes/Int';

export type TImmunizationProtocolApplied = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  series?: string;
  authority?: TReference;
  targetDisease?: TCodeableConcept[];
  doseNumberPositiveInt?: TInt;
  doseNumberString?: string;
  seriesDosesPositiveInt?: TInt;
  seriesDosesString?: string;
};
