/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUrl } from '../simpleTypes/Url';
import { TReference } from '../partials/Reference';

export type TImplementationGuidePage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  nameUrl?: TUrl;
  nameReference?: TReference;
  title: string;
  generation: string;
  page?: TImplementationGuidePage[];
};
