/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TCanonical } from '../simpleTypes/Canonical';
import { TId } from '../simpleTypes/Id';

export type TImplementationGuideResource = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  reference: TReference;
  fhirVersion?: string[];
  name?: string;
  description?: string;
  exampleBoolean?: boolean;
  exampleCanonical?: TCanonical;
  groupingId?: TId;
};
