 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TImplementationGuidePage1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  title?: string;
  anchor?: string[];
};
