 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TId } from '../simpleTypes/Id';

export type TImplementationGuideDependsOn = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  uri: TCanonical;
  packageId?: TId;
  version?: string;
};
