/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableReference } from '../partials/CodeableReference';
import { TRatio } from '../partials/Ratio';
import { TRatioRange } from '../partials/RatioRange';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TIngredientReferenceStrength = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  substance?: TCodeableReference;
  strengthRatio?: TRatio;
  strengthRatioRange?: TRatioRange;
  measurementPoint?: string;
  country?: TCodeableConcept[];
};
