 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';

export type TIngredientManufacturer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role?: string;
  manufacturer: TReference;
};
