/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TInsurancePlanLimit } from '../partials/InsurancePlanLimit';

export type TInsurancePlanBenefit = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  requirement?: string;
  limit?: TInsurancePlanLimit[];
};
