/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from '../partials/Reference';

export type TListEntry = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  flag?: TCodeableConcept;
  deleted?: boolean;
  date?: TDateTime;
  item: TReference;
};
