 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TMedicationRequestSubstitution = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  allowedBoolean?: boolean;
  allowedCodeableConcept?: TCodeableConcept;
  reason?: TCodeableConcept;
};
