 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';

export type TMedicationDispenseSubstitution = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  wasSubstituted: boolean;
  type?: TCodeableConcept;
  reason?: TCodeableConcept[];
  responsibleParty?: TReference[];
};
