 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TMedicinalProductDefinitionNamePart = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  part: string;
  type: TCodeableConcept;
};
