/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TContactPoint } from '../partials/ContactPoint';
import { TUrl } from '../simpleTypes/Url';

export type TMessageHeaderSource = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  software?: string;
  version?: string;
  contact?: TContactPoint;
  endpoint: TUrl;
};
