 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TUrl } from '../simpleTypes/Url';

export type TMessageHeaderDestination = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  target?: TReference;
  endpoint: TUrl;
  receiver?: TReference;
};
