/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TReference } from '../partials/Reference';

export type TMolecularSequenceVariant = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  start?: TInt;
  end?: TInt;
  observedAllele?: string;
  referenceAllele?: string;
  cigar?: string;
  variantPointer?: TReference;
};
