 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TXhtml } from '../simpleTypes/Xhtml';

export type TNarrative = {
  id?: string;
  extension?: TExtension[];
  status: string;
  div: TXhtml;
};
