/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TTiming } from '../partials/Timing';
import { TQuantity } from '../partials/Quantity';

export type TNutritionOrderSupplement = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  productName?: string;
  schedule?: TTiming[];
  quantity?: TQuantity;
  instruction?: string;
};
