 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TNutritionOrderAdministration } from '../partials/NutritionOrderAdministration';

export type TNutritionOrderEnteralFormula = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  baseFormulaType?: TCodeableConcept;
  baseFormulaProductName?: string;
  additiveType?: TCodeableConcept;
  additiveProductName?: string;
  caloricDensity?: TQuantity;
  routeofAdministration?: TCodeableConcept;
  administration?: TNutritionOrderAdministration[];
  maxVolumeToDeliver?: TQuantity;
  administrationInstruction?: string;
};
