/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableReference } from '../partials/CodeableReference';
import { TRatio } from '../partials/Ratio';

export type TNutritionProductNutrient = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  item?: TCodeableReference;
  amount?: TRatio[];
};
