 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TQuantity } from '../partials/Quantity';
import { TIdentifier } from '../partials/Identifier';
import { TDateTime } from '../simpleTypes/DateTime';

export type TNutritionProductInstance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  quantity?: TQuantity;
  identifier?: TIdentifier[];
  lotNumber?: string;
  expiry?: TDateTime;
  useBy?: TDateTime;
};
