 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TNutritionOrderTexture = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  modifier?: TCodeableConcept;
  foodType?: TCodeableConcept;
};
