 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TRange } from '../partials/Range';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TObservationDefinitionQualifiedInterval = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category?: string;
  range?: TRange;
  context?: TCodeableConcept;
  appliesTo?: TCodeableConcept[];
  gender?: string;
  age?: TRange;
  gestationalAge?: TRange;
  condition?: string;
};
