 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';

export type TOperationOutcomeIssue = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  severity: string;
  code: string;
  details?: TCodeableConcept;
  diagnostics?: string;
  location?: string[];
  expression?: string[];
};
