/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TCanonical } from '../simpleTypes/Canonical';
import { TOperationDefinitionBinding } from '../partials/OperationDefinitionBinding';
import { TOperationDefinitionReferencedFrom } from '../partials/OperationDefinitionReferencedFrom';

export type TOperationDefinitionParameter = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  use: string;
  min: TInt;
  max: string;
  documentation?: string;
  type?: string;
  targetProfile?: TCanonical[];
  searchType?: string;
  binding?: TOperationDefinitionBinding;
  referencedFrom?: TOperationDefinitionReferencedFrom[];
  part?: TOperationDefinitionParameter[];
};
