/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TCanonical } from '../simpleTypes/Canonical';

export type TParameterDefinition = {
  id?: string;
  extension?: TExtension[];
  name?: string;
  use: string;
  min?: TInt;
  max?: string;
  documentation?: string;
  type: string;
  profile?: TCanonical;
};
