/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TPaymentReconciliationProcessNote = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: string;
  text?: string;
};
