 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDateTime } from '../simpleTypes/DateTime';

export type TPeriod = {
  id?: string;
  extension?: TExtension[];
  start?: TDateTime;
  end?: TDateTime;
};
