/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TPeriod } from '../partials/Period';

export type TPractitionerRoleNotAvailable = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description: string;
  during?: TPeriod;
};
