 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';
import { TProvenanceAgent } from '../partials/ProvenanceAgent';

export type TProvenanceEntity = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role: string;
  what: TReference;
  agent?: TProvenanceAgent[];
};
