/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TDate } from '../simpleTypes/Date';
import { TTime } from '../simpleTypes/Time';
import { TCoding } from '../partials/Coding';
import { TReference } from '../partials/Reference';

export type TQuestionnaireAnswerOption = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  valueInteger?: TInt;
  valueDate?: TDate;
  valueTime?: TTime;
  valueString?: string;
  valueCoding?: TCoding;
  valueReference?: TReference;
  initialSelected?: boolean;
};
