/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';
import { TQuestionnaireResponseAnswer } from '../partials/QuestionnaireResponseAnswer';

export type TQuestionnaireResponseItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  linkId: string;
  definition?: TUri;
  text?: string;
  answer?: TQuestionnaireResponseAnswer[];
  item?: TQuestionnaireResponseItem[];
};
