 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';

export type TRequestGroupRelatedAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  actionId: TId;
  relationship: string;
  offsetDuration?: TQuantity;
  offsetRange?: TRange;
};
