 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TQuantity } from '../partials/Quantity';
import { TSpecimenDefinitionAdditive } from '../partials/SpecimenDefinitionAdditive';

export type TSpecimenDefinitionContainer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  material?: TCodeableConcept;
  type?: TCodeableConcept;
  cap?: TCodeableConcept;
  description?: string;
  capacity?: TQuantity;
  minimumVolumeQuantity?: TQuantity;
  minimumVolumeString?: string;
  additive?: TSpecimenDefinitionAdditive[];
  preparation?: string;
};
