/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSpecimenDefinitionContainer } from '../partials/SpecimenDefinitionContainer';
import { TQuantity } from '../partials/Quantity';
import { TSpecimenDefinitionHandling } from '../partials/SpecimenDefinitionHandling';

export type TSpecimenDefinitionTypeTested = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  isDerived?: boolean;
  type?: TCodeableConcept;
  preference: string;
  container?: TSpecimenDefinitionContainer;
  requirement?: string;
  retentionTime?: TQuantity;
  rejectionCriterion?: TCodeableConcept[];
  handling?: TSpecimenDefinitionHandling[];
};
