/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TRange } from '../partials/Range';
import { TQuantity } from '../partials/Quantity';

export type TSpecimenDefinitionHandling = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  temperatureQualifier?: TCodeableConcept;
  temperatureRange?: TRange;
  maxDuration?: TQuantity;
  instruction?: string;
};
