/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';

export type TStructureMapInput = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: TId;
  type?: string;
  mode: string;
  documentation?: string;
};
