/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TId } from '../simpleTypes/Id';
import { TStructureMapInput } from '../partials/StructureMapInput';
import { TStructureMapRule } from '../partials/StructureMapRule';

export type TStructureMapGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: TId;
  extends_?: TId;
  typeMode: string;
  documentation?: string;
  input: TStructureMapInput[];
  rule: TStructureMapRule[];
};
