 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TElementDefinition } from '../partials/ElementDefinition';

export type TStructureDefinitionDifferential = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  element: TElementDefinition[];
};
