 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUri } from '../simpleTypes/Uri';
import { TSubscriptionTopicQueryCriteria } from '../partials/SubscriptionTopicQueryCriteria';

export type TSubscriptionTopicResourceTrigger = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: TMarkdown;
  resource: TUri;
  supportedInteraction?: string[];
  queryCriteria?: TSubscriptionTopicQueryCriteria;
  fhirPathCriteria?: string;
};
