 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSubstanceDefinitionMolecularWeight } from '../partials/SubstanceDefinitionMolecularWeight';
import { TReference } from '../partials/Reference';
import { TSubstanceDefinitionRepresentation } from '../partials/SubstanceDefinitionRepresentation';

export type TSubstanceDefinitionStructure = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  stereochemistry?: TCodeableConcept;
  opticalActivity?: TCodeableConcept;
  molecularFormula?: string;
  molecularFormulaByMoiety?: string;
  molecularWeight?: TSubstanceDefinitionMolecularWeight;
  technique?: TCodeableConcept[];
  sourceDocument?: TReference[];
  representation?: TSubstanceDefinitionRepresentation[];
};
