 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUri } from '../simpleTypes/Uri';

export type TSubscriptionTopicCanFilterBy = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: TMarkdown;
  resource?: TUri;
  filterParameter: string;
  filterDefinition?: TUri;
  modifier?: string[];
};
