/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSubstanceDefinitionOfficial } from '../partials/SubstanceDefinitionOfficial';
import { TReference } from '../partials/Reference';

export type TSubstanceDefinitionName = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  type?: TCodeableConcept;
  status?: TCodeableConcept;
  preferred?: boolean;
  language?: TCodeableConcept[];
  domain?: TCodeableConcept[];
  jurisdiction?: TCodeableConcept[];
  synonym?: TSubstanceDefinitionName[];
  translation?: TSubstanceDefinitionName[];
  official?: TSubstanceDefinitionOfficial[];
  source?: TReference[];
};
