/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TIdentifier } from '../partials/Identifier';
import { TQuantity } from '../partials/Quantity';

export type TSubstanceDefinitionMoiety = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role?: TCodeableConcept;
  identifier?: TIdentifier;
  name?: string;
  stereochemistry?: TCodeableConcept;
  opticalActivity?: TCodeableConcept;
  molecularFormula?: string;
  amountQuantity?: TQuantity;
  amountString?: string;
  measurementType?: TCodeableConcept;
};
