/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TTerminologyCapabilitiesFilter } from '../partials/TerminologyCapabilitiesFilter';

export type TTerminologyCapabilitiesVersion = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: string;
  isDefault?: boolean;
  compositional?: boolean;
  language?: string[];
  filter?: TTerminologyCapabilitiesFilter[];
  property?: string[];
};
