 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUri } from '../simpleTypes/Uri';

export type TTestReportOperation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  result: string;
  message?: TMarkdown;
  detail?: TUri;
};
