 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TUri } from '../simpleTypes/Uri';
import { TCanonical } from '../simpleTypes/Canonical';

export type TTestScriptCapability = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  required: boolean;
  validated: boolean;
  description?: string;
  origin?: TInt[];
  destination?: TInt;
  link?: TUri[];
  capabilities: TCanonical;
};
