/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TTestScriptRequestHeader = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  field: string;
  value: string;
};
