/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TTestScriptAction1 } from '../partials/TestScriptAction1';

export type TTestScriptTest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  description?: string;
  action: TTestScriptAction1[];
};
