 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TTestReportAssert = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  result: string;
  message?: TMarkdown;
  detail?: string;
};
