/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TReference } from '../partials/Reference';

export type TTestScriptFixture = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  autocreate: boolean;
  autodelete: boolean;
  resource?: TReference;
};
