 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TUri } from '../simpleTypes/Uri';

export type TTestScriptLink = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url: TUri;
  description?: string;
};
