 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TPeriod } from '../partials/Period';
import { TInt } from '../simpleTypes/Int';
import { TDecimal } from '../simpleTypes/Decimal';
import { TTime } from '../simpleTypes/Time';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TTimingRepeat = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  boundsDuration?: TQuantity;
  boundsRange?: TRange;
  boundsPeriod?: TPeriod;
  count?: TInt;
  countMax?: TInt;
  duration?: TDecimal;
  durationMax?: TDecimal;
  durationUnit?: string;
  frequency?: TInt;
  frequencyMax?: TInt;
  period?: TDecimal;
  periodMax?: TDecimal;
  periodUnit?: string;
  dayOfWeek?: string[];
  timeOfDay?: TTime[];
  when?: string[];
  offset?: TUnsignedInt;
};
