 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TValueSetDesignation } from '../partials/ValueSetDesignation';

export type TValueSetConcept = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  display?: string;
  designation?: TValueSetDesignation[];
};
