/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TDate } from '../simpleTypes/Date';
import { TValueSetInclude } from '../partials/ValueSetInclude';

export type TValueSetCompose = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  lockedDate?: TDate;
  inactive?: boolean;
  include: TValueSetInclude[];
  exclude?: TValueSetInclude[];
};
