 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';

export type TValueSetFilter = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  property: string;
  op: string;
  value: string;
};
