/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from '../partials/Extension';
import { TInt } from '../simpleTypes/Int';
import { TDecimal } from '../simpleTypes/Decimal';
import { TUri } from '../simpleTypes/Uri';
import { TDateTime } from '../simpleTypes/DateTime';

export type TValueSetParameter = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  valueString?: string;
  valueBoolean?: boolean;
  valueInteger?: TInt;
  valueDecimal?: TDecimal;
  valueUri?: TUri;
  valueCode?: string;
  valueDateTime?: TDateTime;
};
