 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TPeriod } from '../partials/Period';
import { TAccountCoverage } from '../partials/AccountCoverage';
import { TAccountGuarantor } from '../partials/AccountGuarantor';

export type TAccount = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status: string;
  type?: TCodeableConcept;
  name?: string;
  subject?: TReference[];
  servicePeriod?: TPeriod;
  coverage?: TAccountCoverage[];
  owner?: TReference;
  description?: string;
  guarantor?: TAccountGuarantor[];
  partOf?: TReference;
};
