/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCapabilityStatementSoftware } from '../partials/CapabilityStatementSoftware';
import { TCapabilityStatementImplementation } from '../partials/CapabilityStatementImplementation';
import { TCapabilityStatementRest } from '../partials/CapabilityStatementRest';
import { TCapabilityStatementMessaging } from '../partials/CapabilityStatementMessaging';
import { TCapabilityStatementDocument } from '../partials/CapabilityStatementDocument';

export type TCapabilityStatement = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url?: TUri;
  version?: string;
  name?: string;
  title?: string;
  status: string;
  experimental?: boolean;
  date: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  copyright?: TMarkdown;
  kind: string;
  instantiates?: TCanonical[];
  imports?: TCanonical[];
  software?: TCapabilityStatementSoftware;
  implementation?: TCapabilityStatementImplementation;
  fhirVersion: string;
  format: string[];
  patchFormat?: string[];
  implementationGuide?: TCanonical[];
  rest?: TCapabilityStatementRest[];
  messaging?: TCapabilityStatementMessaging[];
  document?: TCapabilityStatementDocument[];
};
