 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TContractContentDefinition } from '../partials/ContractContentDefinition';
import { TContractTerm } from '../partials/ContractTerm';
import { TContractSigner } from '../partials/ContractSigner';
import { TContractFriendly } from '../partials/ContractFriendly';
import { TContractLegal } from '../partials/ContractLegal';
import { TContractRule } from '../partials/ContractRule';
import { TAttachment } from '../partials/Attachment';

export type TContract = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  url?: TUri;
  version?: string;
  status?: string;
  legalState?: TCodeableConcept;
  instantiatesCanonical?: TReference;
  instantiatesUri?: TUri;
  contentDerivative?: TCodeableConcept;
  issued?: TDateTime;
  applies?: TPeriod;
  expirationType?: TCodeableConcept;
  subject?: TReference[];
  authority?: TReference[];
  domain?: TReference[];
  site?: TReference[];
  name?: string;
  title?: string;
  subtitle?: string;
  alias?: string[];
  author?: TReference;
  scope?: TCodeableConcept;
  topicCodeableConcept?: TCodeableConcept;
  topicReference?: TReference;
  type?: TCodeableConcept;
  subType?: TCodeableConcept[];
  contentDefinition?: TContractContentDefinition;
  term?: TContractTerm[];
  supportingInfo?: TReference[];
  relevantHistory?: TReference[];
  signer?: TContractSigner[];
  friendly?: TContractFriendly[];
  legal?: TContractLegal[];
  rule?: TContractRule[];
  legallyBindingAttachment?: TAttachment;
  legallyBindingReference?: TReference;
};
