 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from '../partials/Period';
import { TDateTime } from '../simpleTypes/DateTime';
import { TCoverageEligibilityResponseInsurance } from '../partials/CoverageEligibilityResponseInsurance';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TCoverageEligibilityResponseError } from '../partials/CoverageEligibilityResponseError';

export type TCoverageEligibilityResponse = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status: string;
  purpose: string[];
  patient: TReference;
  servicedDate?: TDate;
  servicedPeriod?: TPeriod;
  created: TDateTime;
  requestor?: TReference;
  request: TReference;
  outcome: string;
  disposition?: string;
  insurer: TReference;
  insurance?: TCoverageEligibilityResponseInsurance[];
  preAuthRef?: string;
  form?: TCodeableConcept;
  error?: TCoverageEligibilityResponseError[];
};
