 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TDocumentManifestRelated } from '../partials/DocumentManifestRelated';

export type TDocumentManifest = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  masterIdentifier?: TIdentifier;
  identifier?: TIdentifier[];
  status: string;
  type?: TCodeableConcept;
  subject?: TReference;
  created?: TDateTime;
  author?: TReference[];
  recipient?: TReference[];
  source?: TUri;
  description?: string;
  content: TReference[];
  related?: TDocumentManifestRelated[];
};
