 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCoding } from '../partials/Coding';
import { TReference } from '../partials/Reference';
import { TContactPoint } from '../partials/ContactPoint';
import { TPeriod } from '../partials/Period';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TUrl } from '../simpleTypes/Url';

export type TEndpoint = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status: string;
  connectionType: TCoding;
  name?: string;
  managingOrganization?: TReference;
  contact?: TContactPoint[];
  period?: TPeriod;
  payloadType: TCodeableConcept[];
  payloadMimeType?: string[];
  address: TUrl;
  header?: string[];
};
