 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TDate } from '../simpleTypes/Date';
import { TQuantity } from '../partials/Quantity';
import { TRange } from '../partials/Range';
import { TAnnotation } from '../partials/Annotation';
import { TFamilyMemberHistoryCondition } from '../partials/FamilyMemberHistoryCondition';

export type TFamilyMemberHistory = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  instantiatesCanonical?: TCanonical[];
  instantiatesUri?: TUri[];
  status: string;
  dataAbsentReason?: TCodeableConcept;
  patient: TReference;
  date?: TDateTime;
  name?: string;
  relationship: TCodeableConcept;
  sex?: TCodeableConcept;
  bornPeriod?: TPeriod;
  bornDate?: TDate;
  bornString?: string;
  ageAge?: TQuantity;
  ageRange?: TRange;
  ageString?: string;
  estimatedAge?: boolean;
  deceasedBoolean?: boolean;
  deceasedAge?: TQuantity;
  deceasedRange?: TRange;
  deceasedDate?: TDate;
  deceasedString?: string;
  reasonCode?: TCodeableConcept[];
  reasonReference?: TReference[];
  note?: TAnnotation[];
  condition?: TFamilyMemberHistoryCondition[];
};
