 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TInt } from '../simpleTypes/Int';

export type TImmunizationEvaluation = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status: string;
  patient: TReference;
  date?: TDateTime;
  authority?: TReference;
  targetDisease: TCodeableConcept;
  immunizationEvent: TReference;
  doseStatus: TCodeableConcept;
  doseStatusReason?: TCodeableConcept[];
  description?: string;
  series?: string;
  doseNumberPositiveInt?: TInt;
  doseNumberString?: string;
  seriesDosesPositiveInt?: TInt;
  seriesDosesString?: string;
};
