 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TIngredientManufacturer } from '../partials/IngredientManufacturer';
import { TIngredientSubstance } from '../partials/IngredientSubstance';

export type TIngredient = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  status: string;
  for_?: TReference[];
  role: TCodeableConcept;
  function_?: TCodeableConcept[];
  allergenicIndicator?: boolean;
  manufacturer?: TIngredientManufacturer[];
  substance: TIngredientSubstance;
};
