 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from '../partials/Period';
import { TRelatedArtifact } from '../partials/RelatedArtifact';
import { TParameterDefinition } from '../partials/ParameterDefinition';
import { TDataRequirement } from '../partials/DataRequirement';
import { TAttachment } from '../partials/Attachment';

export type TLibrary = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url?: TUri;
  identifier?: TIdentifier[];
  version?: string;
  name?: string;
  title?: string;
  subtitle?: string;
  status: string;
  experimental?: boolean;
  type: TCodeableConcept;
  subjectCodeableConcept?: TCodeableConcept;
  subjectReference?: TReference;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  usage?: string;
  copyright?: TMarkdown;
  approvalDate?: TDate;
  lastReviewDate?: TDate;
  effectivePeriod?: TPeriod;
  topic?: TCodeableConcept[];
  author?: TContactDetail[];
  editor?: TContactDetail[];
  reviewer?: TContactDetail[];
  endorser?: TContactDetail[];
  relatedArtifact?: TRelatedArtifact[];
  parameter?: TParameterDefinition[];
  dataRequirement?: TDataRequirement[];
  content?: TAttachment[];
};
