 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCoding } from '../partials/Coding';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TContactPoint } from '../partials/ContactPoint';
import { TAddress } from '../partials/Address';
import { TLocationPosition } from '../partials/LocationPosition';
import { TReference } from '../partials/Reference';
import { TLocationHoursOfOperation } from '../partials/LocationHoursOfOperation';

export type TLocation = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status?: string;
  operationalStatus?: TCoding;
  name?: string;
  alias?: string[];
  description?: string;
  mode?: string;
  type?: TCodeableConcept[];
  telecom?: TContactPoint[];
  address?: TAddress;
  physicalType?: TCodeableConcept;
  position?: TLocationPosition;
  managingOrganization?: TReference;
  partOf?: TReference;
  hoursOfOperation?: TLocationHoursOfOperation[];
  availabilityExceptions?: string;
  endpoint?: TReference[];
};
