 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TMarketingStatus } from '../partials/MarketingStatus';
import { TCodeableReference } from '../partials/CodeableReference';
import { TReference } from '../partials/Reference';
import { TMedicinalProductDefinitionContact } from '../partials/MedicinalProductDefinitionContact';
import { TCoding } from '../partials/Coding';
import { TMedicinalProductDefinitionName } from '../partials/MedicinalProductDefinitionName';
import { TMedicinalProductDefinitionCrossReference } from '../partials/MedicinalProductDefinitionCrossReference';
import { TMedicinalProductDefinitionOperation } from '../partials/MedicinalProductDefinitionOperation';
import { TMedicinalProductDefinitionCharacteristic } from '../partials/MedicinalProductDefinitionCharacteristic';

export type TMedicinalProductDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  type?: TCodeableConcept;
  domain?: TCodeableConcept;
  version?: string;
  status?: TCodeableConcept;
  statusDate?: TDateTime;
  description?: TMarkdown;
  combinedPharmaceuticalDoseForm?: TCodeableConcept;
  route?: TCodeableConcept[];
  indication?: TMarkdown;
  legalStatusOfSupply?: TCodeableConcept;
  additionalMonitoringIndicator?: TCodeableConcept;
  specialMeasures?: TCodeableConcept[];
  pediatricUseIndicator?: TCodeableConcept;
  classification?: TCodeableConcept[];
  marketingStatus?: TMarketingStatus[];
  packagedMedicinalProduct?: TCodeableConcept[];
  ingredient?: TCodeableConcept[];
  impurity?: TCodeableReference[];
  attachedDocument?: TReference[];
  masterFile?: TReference[];
  contact?: TMedicinalProductDefinitionContact[];
  clinicalTrial?: TReference[];
  code?: TCoding[];
  name: TMedicinalProductDefinitionName[];
  crossReference?: TMedicinalProductDefinitionCrossReference[];
  operation?: TMedicinalProductDefinitionOperation[];
  characteristic?: TMedicinalProductDefinitionCharacteristic[];
};
