 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TInt } from '../simpleTypes/Int';
import { TReference } from '../partials/Reference';
import { TQuantity } from '../partials/Quantity';
import { TMolecularSequenceReferenceSeq } from '../partials/MolecularSequenceReferenceSeq';
import { TMolecularSequenceVariant } from '../partials/MolecularSequenceVariant';
import { TMolecularSequenceQuality } from '../partials/MolecularSequenceQuality';
import { TMolecularSequenceRepository } from '../partials/MolecularSequenceRepository';
import { TMolecularSequenceStructureVariant } from '../partials/MolecularSequenceStructureVariant';

export type TMolecularSequence = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  type?: string;
  coordinateSystem: TInt;
  patient?: TReference;
  specimen?: TReference;
  device?: TReference;
  performer?: TReference;
  quantity?: TQuantity;
  referenceSeq?: TMolecularSequenceReferenceSeq;
  variant?: TMolecularSequenceVariant[];
  observedSeq?: string;
  quality?: TMolecularSequenceQuality[];
  readCoverage?: TInt;
  repository?: TMolecularSequenceRepository[];
  pointer?: TReference[];
  structureVariant?: TMolecularSequenceStructureVariant[];
};
