/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TIdentifier } from '../partials/Identifier';
import { TObservationDefinitionQuantitativeDetails } from '../partials/ObservationDefinitionQuantitativeDetails';
import { TObservationDefinitionQualifiedInterval } from '../partials/ObservationDefinitionQualifiedInterval';
import { TReference } from '../partials/Reference';

export type TObservationDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category?: TCodeableConcept[];
  code: TCodeableConcept;
  identifier?: TIdentifier[];
  permittedDataType?: string[];
  multipleResultsAllowed?: boolean;
  method?: TCodeableConcept;
  preferredReportName?: string;
  quantitativeDetails?: TObservationDefinitionQuantitativeDetails;
  qualifiedInterval?: TObservationDefinitionQualifiedInterval[];
  validCodedValueSet?: TReference;
  normalCodedValueSet?: TReference;
  abnormalCodedValueSet?: TReference;
  criticalCodedValueSet?: TReference;
};
