 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TCanonical } from '../simpleTypes/Canonical';
import { TOperationDefinitionParameter } from '../partials/OperationDefinitionParameter';
import { TOperationDefinitionOverload } from '../partials/OperationDefinitionOverload';

export type TOperationDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url?: TUri;
  version?: string;
  name: string;
  title?: string;
  status: string;
  kind: string;
  experimental?: boolean;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  affectsState?: boolean;
  code: string;
  comment?: TMarkdown;
  base?: TCanonical;
  resource?: string[];
  system: boolean;
  type: boolean;
  instance: boolean;
  inputProfile?: TCanonical;
  outputProfile?: TCanonical;
  parameter?: TOperationDefinitionParameter[];
  overload?: TOperationDefinitionOverload[];
};
