 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from '../partials/Quantity';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TPackagedProductDefinitionLegalStatusOfSupply } from '../partials/PackagedProductDefinitionLegalStatusOfSupply';
import { TMarketingStatus } from '../partials/MarketingStatus';
import { TPackagedProductDefinitionPackage } from '../partials/PackagedProductDefinitionPackage';

export type TPackagedProductDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  name?: string;
  type?: TCodeableConcept;
  packageFor?: TReference[];
  status?: TCodeableConcept;
  statusDate?: TDateTime;
  containedItemQuantity?: TQuantity[];
  description?: TMarkdown;
  legalStatusOfSupply?: TPackagedProductDefinitionLegalStatusOfSupply[];
  marketingStatus?: TMarketingStatus[];
  characteristic?: TCodeableConcept[];
  copackagedIndicator?: boolean;
  manufacturer?: TReference[];
  package?: TPackagedProductDefinitionPackage;
};
