/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TCanonical } from '../simpleTypes/Canonical';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from '../partials/Period';
import { TRelatedArtifact } from '../partials/RelatedArtifact';
import { TPlanDefinitionGoal } from '../partials/PlanDefinitionGoal';
import { TPlanDefinitionAction } from '../partials/PlanDefinitionAction';

export type TPlanDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url?: TUri;
  identifier?: TIdentifier[];
  version?: string;
  name?: string;
  title?: string;
  subtitle?: string;
  type?: TCodeableConcept;
  status: string;
  experimental?: boolean;
  subjectCodeableConcept?: TCodeableConcept;
  subjectReference?: TReference;
  subjectCanonical?: TCanonical;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  usage?: string;
  copyright?: TMarkdown;
  approvalDate?: TDate;
  lastReviewDate?: TDate;
  effectivePeriod?: TPeriod;
  topic?: TCodeableConcept[];
  author?: TContactDetail[];
  editor?: TContactDetail[];
  reviewer?: TContactDetail[];
  endorser?: TContactDetail[];
  relatedArtifact?: TRelatedArtifact[];
  library?: TCanonical[];
  goal?: TPlanDefinitionGoal[];
  action?: TPlanDefinitionAction[];
};
