 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSearchParameterComponent } from '../partials/SearchParameterComponent';

export type TSearchParameter = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url: TUri;
  version?: string;
  name: string;
  derivedFrom?: TCanonical;
  status: string;
  experimental?: boolean;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  code: string;
  base: string[];
  type: string;
  expression?: string;
  xpath?: string;
  xpathUsage?: string;
  target?: string[];
  multipleOr?: boolean;
  multipleAnd?: boolean;
  comparator?: string[];
  modifier?: string[];
  chain?: string[];
  component?: TSearchParameterComponent[];
};
