 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TSpecimenDefinitionTypeTested } from '../partials/SpecimenDefinitionTypeTested';

export type TSpecimenDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  typeCollected?: TCodeableConcept;
  patientPreparation?: TCodeableConcept[];
  timeAspect?: string;
  collection?: TCodeableConcept[];
  typeTested?: TSpecimenDefinitionTypeTested[];
};
