 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TCoding } from '../partials/Coding';
import { TStructureDefinitionMapping } from '../partials/StructureDefinitionMapping';
import { TStructureDefinitionContext } from '../partials/StructureDefinitionContext';
import { TCanonical } from '../simpleTypes/Canonical';
import { TStructureDefinitionSnapshot } from '../partials/StructureDefinitionSnapshot';
import { TStructureDefinitionDifferential } from '../partials/StructureDefinitionDifferential';

export type TStructureDefinition = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url: TUri;
  identifier?: TIdentifier[];
  version?: string;
  name: string;
  title?: string;
  status: string;
  experimental?: boolean;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  purpose?: TMarkdown;
  copyright?: TMarkdown;
  keyword?: TCoding[];
  fhirVersion?: string;
  mapping?: TStructureDefinitionMapping[];
  kind: string;
  abstract: boolean;
  context?: TStructureDefinitionContext[];
  contextInvariant?: string[];
  type: TUri;
  baseDefinition?: TCanonical;
  derivation?: string;
  snapshot?: TStructureDefinitionSnapshot;
  differential?: TStructureDefinitionDifferential;
};
