 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TContactPoint } from '../partials/ContactPoint';
import { TInstant } from '../simpleTypes/Instant';
import { TSubscriptionChannel } from '../partials/SubscriptionChannel';

export type TSubscription = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  status: string;
  contact?: TContactPoint[];
  end?: TInstant;
  reason: string;
  criteria: string;
  error?: string;
  channel: TSubscriptionChannel;
};
