 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TReference } from '../partials/Reference';
import { TQuantity } from '../partials/Quantity';
import { TSupplyRequestParameter } from '../partials/SupplyRequestParameter';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from '../partials/Period';
import { TTiming } from '../partials/Timing';

export type TSupplyRequest = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status?: string;
  category?: TCodeableConcept;
  priority?: string;
  itemCodeableConcept?: TCodeableConcept;
  itemReference?: TReference;
  quantity: TQuantity;
  parameter?: TSupplyRequestParameter[];
  occurrenceDateTime?: TDateTime;
  occurrencePeriod?: TPeriod;
  occurrenceTiming?: TTiming;
  authoredOn?: TDateTime;
  requester?: TReference;
  supplier?: TReference[];
  reasonCode?: TCodeableConcept[];
  reasonReference?: TReference[];
  deliverFrom?: TReference;
  deliverTo?: TReference;
};
