 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TReference } from '../partials/Reference';
import { TDecimal } from '../simpleTypes/Decimal';
import { TDateTime } from '../simpleTypes/DateTime';
import { TTestReportParticipant } from '../partials/TestReportParticipant';
import { TTestReportSetup } from '../partials/TestReportSetup';
import { TTestReportTest } from '../partials/TestReportTest';
import { TTestReportTeardown } from '../partials/TestReportTeardown';

export type TTestReport = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  name?: string;
  status: string;
  testScript: TReference;
  result: string;
  score?: TDecimal;
  tester?: string;
  issued?: TDateTime;
  participant?: TTestReportParticipant[];
  setup?: TTestReportSetup;
  test?: TTestReportTest[];
  teardown?: TTestReportTeardown;
};
