/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TContactDetail } from '../partials/ContactDetail';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUsageContext } from '../partials/UsageContext';
import { TCodeableConcept } from '../partials/CodeableConcept';
import { TValueSetCompose } from '../partials/ValueSetCompose';
import { TValueSetExpansion } from '../partials/ValueSetExpansion';

export type TValueSet = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  url?: TUri;
  identifier?: TIdentifier[];
  version?: string;
  name?: string;
  title?: string;
  status: string;
  experimental?: boolean;
  date?: TDateTime;
  publisher?: string;
  contact?: TContactDetail[];
  description?: TMarkdown;
  useContext?: TUsageContext[];
  jurisdiction?: TCodeableConcept[];
  immutable?: boolean;
  purpose?: TMarkdown;
  copyright?: TMarkdown;
  compose?: TValueSetCompose;
  expansion?: TValueSetExpansion;
};
