 
 
// This file is auto-generated by generate_types so do not edit manually

import { TMeta } from '../partials/Meta';
import { TUri } from '../simpleTypes/Uri';
import { TNarrative } from '../partials/Narrative';
import { TResourceContainer } from '../simpleTypes/ResourceContainer';
import { TExtension } from '../partials/Extension';
import { TIdentifier } from '../partials/Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from '../partials/Reference';
import { TVisionPrescriptionLensSpecification } from '../partials/VisionPrescriptionLensSpecification';

export type TVisionPrescription = {
  resourceType?: string;
  id?: string;
  meta?: TMeta;
  implicitRules?: TUri;
  language?: string;
  text?: TNarrative;
  contained?: TResourceContainer[];
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  status: string;
  created: TDateTime;
  patient: TReference;
  encounter?: TReference;
  dateWritten: TDateTime;
  prescriber: TReference;
  lensSpecification: TVisionPrescriptionLensSpecification[];
};
